@extends('layouts.app')

@section('title', 'Feedback & Rating - Gayatri CRM')

@section('content')
    <x-ui.page-header eyebrow="Feedback" title="Feedback & Rating" description="Pantau rating treatment, komentar customer, dan komplain yang perlu ditangani cepat.">
        <x-slot name="actions"><a class="button button-secondary" href="{{ route('admin.followups.index') }}"><i data-lucide="phone-forwarded"></i> Follow-Up</a></x-slot>
    </x-ui.page-header>
    @if(session('status'))<div class="card" style="margin-bottom:1rem;border-color:rgba(143,174,139,.55);"><div class="card-body" style="color:#3f6d3d;">{{ session('status') }}</div></div>@endif
    <div class="card" style="margin-bottom:1rem;"><div class="card-body"><form method="GET" class="grid grid-3"><select class="input" name="status"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select><select class="input" name="rating"><option value="">Semua rating</option>@foreach([5,4,3,2,1] as $rating)<option value="{{ $rating }}" @selected((int) request('rating')===$rating)>{{ $rating }} bintang</option>@endforeach</select><button class="button button-secondary" type="submit"><i data-lucide="search"></i> Filter</button></form></div></div>
    <div class="card"><div class="card-body"><table class="table-card"><thead><tr><th>Customer</th><th>Booking</th><th>Rating</th><th>Pesan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($feedback as $item)<tr><td data-label="Customer">{{ $item->customer?->name }}<br><span class="muted">{{ $item->customer?->whatsapp_number }}</span></td><td data-label="Booking">{{ $item->booking?->booking_code ?: '-' }}<br><span class="muted">{{ $item->booking?->service?->name ?: '-' }}</span></td><td data-label="Rating">{{ $item->rating ? $item->rating.'/5' : '-' }}</td><td data-label="Pesan">{{ $item->message ?: '-' }}</td><td data-label="Status"><span class="badge {{ $item->status === 'escalated' ? 'badge-red' : 'badge-gold' }}">{{ $item->status }}</span></td><td data-label="Aksi">@if($item->status !== 'responded')<form method="POST" action="{{ route('admin.feedback.respond', $item) }}">@csrf<button class="button button-secondary" type="submit">Tandai Ditangani</button></form>@else<span class="muted">{{ $item->responded_at?->format('d M Y H:i') }}</span>@endif</td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:2rem;">Belum ada feedback.</td></tr>@endforelse</tbody></table><div style="margin-top:1rem;">{{ $feedback->links() }}</div></div></div>
@endsection
