@extends('layouts.app')

@section('title', 'Review Approval - Gayatri CRM')

@section('content')
    <x-ui.page-header eyebrow="AI Data Automation" title="Review Approval" description="Periksa proposed data sebelum menjalankan aksi ke database.">
        <x-slot name="actions"><a class="button button-secondary" href="{{ route('admin.ai.data-automation.approvals.index') }}"><i data-lucide="arrow-left"></i> Kembali</a></x-slot>
    </x-ui.page-header>
    @if($errors->any())<div class="card" style="margin-bottom:1rem;border-color:rgba(201,122,106,.55);"><div class="card-body" style="color:#7a3228;">{{ $errors->first() }}</div></div>@endif
    <section class="grid grid-2"><div class="card"><div class="card-body"><h2 class="section-title">Ringkasan Approval</h2><ul class="soft-list"><li class="soft-list-item"><span>Customer</span><strong>{{ $approval->customer?->name ?: '-' }}</strong></li><li class="soft-list-item"><span>Target</span><strong>{{ $approval->target_entity }}</strong></li><li class="soft-list-item"><span>Action</span><strong>{{ $approval->action }}</strong></li><li class="soft-list-item"><span>Status</span><span class="badge badge-gold">{{ $approval->status }}</span></li><li class="soft-list-item"><span>Expires</span><strong>{{ $approval->expires_at?->format('d M Y H:i') ?: '-' }}</strong></li></ul></div></div><div class="card"><div class="card-body"><h2 class="section-title">Pesan Customer</h2><p class="muted">{{ $approval->extractedData?->message?->content ?: '-' }}</p></div></div></section>
    <div class="card" style="margin-top:1rem;"><div class="card-body"><h2 class="section-title">Proposed Data</h2><pre style="white-space:pre-wrap;">{{ json_encode($approval->proposed_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div></div>
    @if($approval->status === 'pending')<section class="grid grid-3" style="margin-top:1rem;"><div class="card"><div class="card-body"><h2 class="section-title">Approve</h2><p class="muted">Menyetujui akan menjalankan action ke database. Booking baru akan menjadi draft; reschedule akan mengubah jadwal booking existing.</p><form method="POST" action="{{ route('admin.ai.data-automation.approvals.approve', $approval) }}">@csrf<button class="button button-primary" type="submit"><i data-lucide="check"></i> Approve</button></form></div></div><div class="card"><div class="card-body"><h2 class="section-title">Edit & Approve</h2><form method="POST" action="{{ route('admin.ai.data-automation.approvals.edit-approve', $approval) }}" class="grid">@csrf<input class="input" name="booking_id" placeholder="Booking ID" value="{{ data_get($approval->proposed_data, 'booking.booking_id') }}"><input class="input" name="service_id" placeholder="Service ID" value="{{ data_get($approval->proposed_data, 'booking.service_id') }}"><input class="input" name="availability_slot_id" placeholder="Availability Slot ID" value="{{ data_get($approval->proposed_data, 'booking.availability_slot_id') }}"><input class="input" type="date" name="booking_date" value="{{ data_get($approval->proposed_data, 'booking.booking_date') }}"><input class="input" type="time" name="start_time" value="{{ substr((string) data_get($approval->proposed_data, 'booking.start_time'), 0, 5) }}"><button class="button button-primary" type="submit"><i data-lucide="edit"></i> Edit & Approve</button></form></div></div><div class="card"><div class="card-body"><h2 class="section-title">Reject</h2><form method="POST" action="{{ route('admin.ai.data-automation.approvals.reject', $approval) }}" class="grid">@csrf<label><span class="muted" style="display:block;margin-bottom:.4rem;font-weight:700;">Alasan Reject</span><textarea class="input" name="rejection_reason" rows="4" required></textarea></label><button class="button button-secondary" type="submit"><i data-lucide="x"></i> Reject</button></form></div></div></section>@endif
@endsection
