@extends('layouts.app')

@section('title', 'Reminder Log - Gayatri CRM')

@section('content')
    <x-ui.page-header eyebrow="Reminder" title="Reminder Otomatis" description="Pantau reminder booking H-1 dan H-0, status pengiriman, dan retry jika gagal." />
    @if(session('status'))<div class="card" style="margin-bottom:1rem;border-color:rgba(143,174,139,.55);"><div class="card-body" style="color:#3f6d3d;">{{ session('status') }}</div></div>@endif
    <div class="card" style="margin-bottom:1rem;"><div class="card-body"><form method="GET" class="grid grid-3"><select class="input" name="status"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select><button class="button button-secondary" type="submit"><i data-lucide="search"></i> Filter</button><a class="button button-secondary" href="{{ route('admin.bookings.index') }}">Booking</a></form></div></div>
    <div class="card"><div class="card-body"><table class="table-card"><thead><tr><th>Customer</th><th>Booking</th><th>Tipe</th><th>Scheduled</th><th>Sent</th><th>Status</th><th>Error</th><th>Aksi</th></tr></thead><tbody>@forelse($reminders as $reminder)<tr><td data-label="Customer">{{ $reminder->customer?->name }}</td><td data-label="Booking">{{ $reminder->booking?->booking_code }}<br><span class="muted">{{ $reminder->booking?->service?->name }}</span></td><td data-label="Tipe">{{ strtoupper($reminder->type) }}</td><td data-label="Scheduled">{{ $reminder->scheduled_at?->format('d M Y H:i') }}</td><td data-label="Sent">{{ $reminder->sent_at?->format('d M Y H:i') ?: '-' }}</td><td data-label="Status"><span class="badge {{ $reminder->status === 'sent' ? 'badge-green' : ($reminder->status === 'failed' ? 'badge-red' : 'badge-gold') }}">{{ $reminder->status }}</span></td><td data-label="Error">{{ Str::limit($reminder->failed_reason ?: '-', 50) }}</td><td data-label="Aksi">@if($reminder->status === 'failed')<form method="POST" action="{{ route('admin.reminders.retry', $reminder) }}">@csrf<button class="button button-secondary" type="submit">Retry</button></form>@else-@endif</td></tr>@empty<tr><td colspan="8" style="text-align:center;padding:2rem;">Belum ada reminder.</td></tr>@endforelse</tbody></table><div style="margin-top:1rem;">{{ $reminders->links() }}</div></div></div>
@endsection
