@extends('layouts.app')

@section('title', 'Test Automation - Gayatri CRM')

@section('content')
    <x-ui.page-header eyebrow="AI Data Automation" title="Test Automation" description="Uji extraction dan rule matching tanpa mengirim WhatsApp atau membuat data final." />
    <section class="grid grid-2"><div class="card"><div class="card-body"><form method="POST" action="{{ route('admin.ai.data-automation.test.run') }}" class="grid">@csrf<label><span class="muted" style="display:block;margin-bottom:.4rem;font-weight:700;">Contoh Pesan Customer</span><textarea class="input" name="message" rows="9" required>{{ old('message', $message ?? '') }}</textarea></label><button class="button button-primary" type="submit"><i data-lucide="sparkles"></i> Jalankan Test</button></form></div></div><div class="card"><div class="card-body"><h2 class="section-title">Hasil</h2>@if($result)<ul class="soft-list"><li class="soft-list-item"><span>Intent</span><span class="badge badge-brown">{{ $result['intent'] }}</span></li><li class="soft-list-item"><span>Confidence</span><strong>{{ number_format($result['confidence_score'] * 100, 0) }}%</strong></li><li class="soft-list-item"><span>Missing Fields</span><strong>{{ implode(', ', $result['missing_fields']) ?: '-' }}</strong></li><li class="soft-list-item"><span>Matching Rule</span><strong>{{ $rule?->name ?: 'Tidak ada rule cocok' }}</strong></li></ul>@else<p class="muted">Masukkan pesan untuk melihat intent, confidence, data terekstrak, missing fields, dan rule yang cocok.</p>@endif</div></div></section>
    @if($result)<section class="grid grid-3" style="margin-top:1rem;"><div class="card"><div class="card-body"><h2 class="section-title">Customer</h2><pre style="white-space:pre-wrap;">{{ json_encode($result['customer'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div></div><div class="card"><div class="card-body"><h2 class="section-title">Booking</h2><pre style="white-space:pre-wrap;">{{ json_encode($result['booking'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div></div><div class="card"><div class="card-body"><h2 class="section-title">Follow-Up</h2><pre style="white-space:pre-wrap;">{{ json_encode($result['followup'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div></div></section>@endif
@endsection
